# Generated by Django 3.1.3 on 2021-02-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(default='', max_length=50)),
                ('modules', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizes', models.CharField(default='', max_length=50)),
                ('assignments', models.CharField(default='', max_length=50)),
                ('marks', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('coursename', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('coursename', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.courses')),
                ('studentname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.students')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.professor'),
        ),
    ]
