# Generated by Django 3.1.3 on 2021-02-27 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20210227_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='auth.user'),
            preserve_default=False,
        ),
    ]
