# Generated by Django 3.1.3 on 2021-02-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
