# Generated by Django 3.1.3 on 2021-02-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='owner',
        ),
    ]
