# Generated by Django 3.1.3 on 2021-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_courses_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='professor',
        ),
        migrations.AddField(
            model_name='courses',
            name='coursedescription',
            field=models.CharField(default='', max_length=150),
        ),
    ]
